version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "02:00"
  open-pull-requests-limit: 15
  reviewers:
  - nikitaodnorob
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.8.0
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.9
  - dependency-name: web-vitals
    versions:
    - 1.1.0
  - dependency-name: webpack
    versions:
    - 4.46.0
  - dependency-name: enzyme-adapter-react-16
    versions:
    - 1.15.6
  - dependency-name: babel-loader
    versions:
    - 8.2.2
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
  - dependency-name: sass-loader
    versions:
    - 10.1.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.5
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
  - dependency-name: ini
    versions:
    - 1.3.8
