name: Build
on:
  push:
   branches:
     - master
  pull_request:
    branches:
      - master

jobs:
  compile:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repository
        uses: actions/checkout@master
      
      - name: Install packages
        run: yarn
      
      - name: Build application
        run: yarn build
