name: Code Style
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Check code style
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repository
        uses: actions/checkout@master

      - name: Run eslint
        run: yarn lint
