name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repository
        uses: actions/checkout@master

      - name: Install packages
        run: yarn

      - name: Test application
        run: yarn test
